version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  
  
  frontend:
    build:
      context: ./frontend/resident-frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend
